---
permissions: [
  "ff_environment_apiKeyCreate",
  "ff_environment_apiKeyDelete",
  "ff_environment_apiKeyView",
  "ff_environment_edit",
  "ff_environment_targetGroupEdit",
  "ff_environment_view",
  "ff_featureflag_configEdit",
  "ff_featureflag_create",
  "ff_featureflag_delete",
  "ff_featureflag_edit",
  "ff_featureflag_rulesEdit",
  "ff_featureflag_toggle",
  "ff_featureflag_view",
  "ff_target_view",
  "ff_targetgroup_delete",
  "ff_targetgroup_edit",
  "ff_targetgroup_view",
  "fme_fmeenvironment_dataExportEdit",
  "fme_fmeenvironment_dataExportView",
  "fme_fmeenvironment_edit",
  "fme_fmeenvironment_sdkApiKeyEdit",
  "fme_fmeenvironment_sdkApiKeyView",
  "fme_fmeenvironment_view",
  "fme_fmeexperiment_edit",
  "fme_fmeexperiment_view",
  "fme_fmefeatureflag_edit",
  "fme_fmefeatureflag_view",
  "fme_fmelargesegment_edit",
  "fme_fmelargesegment_view",
  "fme_fmemetric_edit",
  "fme_fmemetric_view",
  "fme_fmesegment_edit",
  "fme_fmesegment_view",
  "fme_fmetraffictype_edit",
  "fme_fmetraffictype_view",
]
