---
permissions: [
  "core_connector_access",
  "core_connector_delete",
  "core_connector_edit",
  "core_connector_view",
  "core_delegate_delete",
  "core_delegate_edit",
  "core_delegate_view",
  "core_delegateconfiguration_delete",
  "core_delegateconfiguration_edit",
  "core_delegateconfiguration_view",
  "core_deploymentfreeze_global",
  "core_deploymentfreeze_manage",
  "core_deploymentfreeze_override",
  "core_environment_access",
  "core_environment_delete",
  "core_environment_edit",
  "core_environment_rollback",
  "core_environment_view",
  "core_environmentgroup_access",
  "core_environmentgroup_delete",
  "core_environmentgroup_edit",
  "core_environmentgroup_view",
  "core_file_access",
  "core_file_delete",
  "core_file_edit",
  "core_file_view",
  "core_pipeline_delete",
  "core_pipeline_edit",
  "core_pipeline_execute",
  "core_pipeline_view",
  "core_project_edit",
  "core_project_view",
  "core_resourcegroup_delete",
  "core_resourcegroup_edit",
  "core_resourcegroup_view",
  "core_role_view",
  "core_secret_access",
  "core_secret_delete",
  "core_secret_edit",
  "core_secret_view",
  "core_service_access",
  "core_service_delete",
  "core_service_edit",
  "core_service_view",
  "core_serviceaccount_delete",
  "core_serviceaccount_edit",
  "core_serviceaccount_manageapikey",
  "core_serviceaccount_view",
  "core_setting_edit",
  "core_template_access",
  "core_template_copy",
  "core_template_delete",
  "core_template_edit",
  "core_template_view",
  "core_user_invite",
  "core_user_view",
  "core_usergroup_view",
  "core_variable_delete",
  "core_variable_edit",
  "core_variable_view"
]
