---
permissions: [
  # Administrative Functions
  "core_audit_view",
  "core_defaultNotificationTemplateSet_delete",
  "core_defaultNotificationTemplateSet_edit",
  "core_defaultNotificationTemplateSet_view",
  "core_notificationchannel_delete",
  "core_notificationchannel_edit",
  "core_notificationchannel_view",
  "core_notificationrule_delete",
  "core_notificationrule_edit",
  "core_notificationrule_view",
  "core_organization_delete",
  "core_organization_edit",
  "core_organization_view",
  "core_resourcegroup_delete",
  "core_resourcegroup_edit",
  "core_resourcegroup_view",
  "core_role_delete",
  "core_role_edit",
  "core_role_view",
  "core_setting_edit",
  "core_setting_view",
  "core_user_invite",
  "core_user_manage",
  "core_user_view",
  "core_usergroup_manage",
  "core_usergroup_view",
  "core_project_create",
  "core_project_delete",
  "core_project_edit",
  "core_project_view",
  "core_serviceaccount_delete",
  "core_serviceaccount_edit",
  "core_serviceaccount_list",
  "core_serviceaccount_manageapikey",
  "core_serviceaccount_view",
  "core_oidcIdToken_create",
]
