---
permissions: [
  # Developer Portal
  "idp_advancedconfiguration_delete",
  "idp_advancedconfiguration_edit",
  "idp_advancedconfiguration_view",
  "idp_catalog_delete",
  "idp_catalog_edit",
  "idp_catalog_view",
  "idp_catalogaccesspolicy_create",
  "idp_catalogaccesspolicy_delete",
  "idp_catalogaccesspolicy_edit",
  "idp_catalogaccesspolicy_view",
  "idp_integration_create",
  "idp_integration_delete",
  "idp_integration_edit",
  "idp_integration_view",
  "idp_layout_edit",
  "idp_layout_view",
  "idp_plugin_delete",
  "idp_plugin_edit",
  "idp_plugin_toggle",
  "idp_plugin_view",
  "idp_scorecard_delete",
  "idp_scorecard_edit",
  "idp_scorecard_view",
  "idp_workflow_delete",
  "idp_workflow_edit",
  "idp_workflow_execute",
  "idp_workflow_view",
]
