---
permissions: [
  "ff_environment_apiKeyView",
  "ff_environment_view",
  "ff_featureflag_create",
  "ff_featureflag_edit",
  "ff_featureflag_toggle",
  "ff_featureflag_view",
  "ff_target_view",
  "ff_targetgroup_view",
  "fme_fmeenvironment_dataExportView",
  "fme_fmeenvironment_sdkApiKeyView",
  "fme_fmeenvironment_view",
  "fme_fmeexperiment_view",
  "fme_fmefeatureflag_edit",
  "fme_fmefeatureflag_view",
  "fme_fmelargesegment_view",
  "fme_fmemetric_view",
  "fme_fmesegment_view",
  "fme_fmetraffictype_view",
]
