---
permissions: [
  # Administrative Functions
  "core_account_edit",
  "core_account_view",
  "core_audit_view",
  "core_authsetting_delete",
  "core_authsetting_edit",
  "core_authsetting_view",
  "core_banner_delete",
  "core_banner_edit",
  "core_banner_view",
  "core_branding_edit", # Requires FF PL_ENABLE_BRANDING
  "core_defaultNotificationTemplateSet_delete",
  "core_defaultNotificationTemplateSet_edit",
  "core_defaultNotificationTemplateSet_view",
  "core_license_edit",
  "core_license_view",
  "core_notificationchannel_delete",
  "core_notificationchannel_edit",
  "core_notificationchannel_view",
  "core_notificationrule_delete",
  "core_notificationrule_edit",
  "core_notificationrule_view",
  "core_organization_create",
  "core_organization_delete",
  "core_organization_edit",
  "core_organization_view",
  "core_resourcegroup_delete",
  "core_resourcegroup_edit",
  "core_resourcegroup_view",
  "core_role_delete",
  "core_role_edit",
  "core_role_view",
  "core_setting_edit",
  "core_setting_view",
  "core_smtp_delete",
  "core_smtp_edit",
  "core_smtp_view",
  "core_streamingDestination_delete",
  "core_streamingDestination_edit",
  "core_streamingDestination_view",
  "core_user_impersonate", # Requires FF PL_ENABLE_USER_IMPERSONATION
  "core_user_invite",
  "core_user_manage",
  "core_user_view",
  "core_usergroup_manage",
  "core_usergroup_view",
  "core_project_create",
  "core_project_delete",
  "core_project_edit",
  "core_project_move",
  "core_project_view",
  "core_serviceaccount_delete",
  "core_serviceaccount_edit",
  "core_serviceaccount_list",
  "core_serviceaccount_manageapikey",
  "core_serviceaccount_view",
  "core_oidcIdToken_create",
]
