---
permissions: [
  # Cloud Cost Management
  "ccm_anomalies_manage",
  "ccm_anomalies_view",
  "ccm_autoStoppingRule_delete",
  "ccm_autoStoppingRule_edit",
  "ccm_autoStoppingRule_view",
  "ccm_budget_delete",
  "ccm_budget_edit",
  "ccm_budget_view",
  "ccm_cloudAssetGovernanceAlert_delete",
  "ccm_cloudAssetGovernanceAlert_edit",
  "ccm_cloudAssetGovernanceAlert_view",
  "ccm_cloudAssetGovernanceEnforcement_delete",
  "ccm_cloudAssetGovernanceEnforcement_edit",
  "ccm_cloudAssetGovernanceEnforcement_view",
  "ccm_cloudAssetGovernanceOverview_view",
  "ccm_cloudAssetGovernanceRuleSet_delete",
  "ccm_cloudAssetGovernanceRuleSet_edit",
  "ccm_cloudAssetGovernanceRuleSet_view",
  "ccm_cloudAssetGovernanceRule_delete",
  "ccm_cloudAssetGovernanceRule_dryExecute",
  "ccm_cloudAssetGovernanceRule_edit",
  "ccm_cloudAssetGovernanceRule_execute",
  "ccm_cloudAssetGovernanceRule_view",
  "ccm_clusterOrchestrator_edit",
  "ccm_clusterOrchestrator_view",
  "ccm_commitmentOrchestrator_edit",
  "ccm_commitmentOrchestrator_view",
  "ccm_costCategory_delete",
  "ccm_costCategory_edit",
  "ccm_costCategory_view",
  "ccm_currencyPreference_edit",
  "ccm_currencyPreference_view",
  "ccm_dataScope_view",
  "ccm_folder_delete",
  "ccm_folder_edit",
  "ccm_folder_view",
  "ccm_loadBalancer_delete",
  "ccm_loadBalancer_edit",
  "ccm_loadBalancer_view",
  "ccm_overview_view",
  "ccm_perspective_delete",
  "ccm_perspective_edit",
  "ccm_perspective_view",
  "ccm_recommendations_manage",
  "ccm_recommendations_view",
]
