---
permissions: [
  # Software Engineering Insights
  "sei_seicollections_create",
  "sei_seicollections_delete",
  "sei_seicollections_edit",
  "sei_seicollections_view",
  "sei_seiconfigurationsettings_create",
  "sei_seiconfigurationsettings_delete",
  "sei_seiconfigurationsettings_edit",
  "sei_seiconfigurationsettings_view",
  "sei_seidatasettings_create",
  "sei_seidatasettings_delete",
  "sei_seidatasettings_edit",
  "sei_seidatasettings_view",
  "sei_seiinsights_create",
  "sei_seiinsights_delete",
  "sei_seiinsights_edit",
  "sei_seiinsights_view",
  "sei_seiinsightscategory_view",
  "sei_seipanorama_view",
  "sei_seiprofiles_create",
  "sei_seiprofiles_delete",
  "sei_seiprofiles_edit",
  "sei_seiprofiles_view",
  "sei_seiteams_create",
  "sei_seiteams_delete",
  "sei_seiteams_edit",
  "sei_seiteams_view",
]
