---
permissions: [
  # Ai SRE
  "iro_alert_config",
  "iro_alert_edit",
  "iro_alert_view",
  "iro_alertrule_create",
  "iro_alertrule_delete",
  "iro_alertrule_edit",
  "iro_incident_config",
  "iro_incident_edit",
  "iro_incident_view",
  "iro_iromanager_create",
  "iro_iromanager_delete",
  "iro_iromanager_edit",
  "iro_iromanager_view",
  "iro_iroworkspace_config",
  "iro_metricsource_create",
  "iro_metricsource_delete",
  "iro_metricsource_edit",
  "iro_metricsource_view",
  "iro_runbook_delete",
  "iro_runbook_edit",
  "iro_runbook_trigger",
  "iro_runbook_view",
  "iro_servicedirectory_delete",
  "iro_servicedirectory_edit",
  "iro_servicedirectory_view",
  "iro_thirdpartyintegrations_delete",
  "iro_thirdpartyintegrations_edit",
  "iro_thirdpartyintegrations_view",
]
