---
permissions: [
  # Infrastructure As Code
  "iac_inventory_approve",
  "iac_inventory_delete",
  "iac_inventory_deletevariable",
  "iac_inventory_edit",
  "iac_inventory_editvariable",
  "iac_inventory_view",
  "iac_playbook_approve",
  "iac_playbook_delete",
  "iac_playbook_deletevariable",
  "iac_playbook_edit",
  "iac_playbook_editvariable",
  "iac_playbook_view",
  "iac_providerregistry_view",
  "iac_registry_view",
  "iac_variableset_delete",
  "iac_variableset_edit",
  "iac_variableset_view",
  "iac_workspace_accessstate",
  "iac_workspace_approve",
  "iac_workspace_delete",
  "iac_workspace_deletevariable",
  "iac_workspace_edit",
  "iac_workspace_editvariable",
  "iac_workspace_executeremoteplan",
  "iac_workspace_view",
]
