---
permissions: [
  # Shared Resources
  "core_accessPolicies_analyze",
  "core_certificate_delete",
  "core_certificate_edit",
  "core_certificate_view",
  "core_connector_access",
  "core_connector_delete",
  "core_connector_edit",
  "core_connector_view",
  "core_delegate_delete",
  "core_delegate_edit",
  "core_delegate_view",
  "core_delegateconfiguration_delete",
  "core_delegateconfiguration_edit",
  "core_delegateconfiguration_view",
  "core_deploymentfreeze_global",
  "core_deploymentfreeze_manage",
  "core_deploymentfreeze_override",
  "core_file_access",
  "core_file_delete",
  "core_file_edit",
  "core_file_view",
  "core_secret_access",
  "core_secret_create",
  "core_secret_delete",
  "core_secret_edit",
  "core_secret_view",
  "core_template_access",
  "core_template_copy",
  "core_template_create",
  "core_template_delete",
  "core_template_edit",
  "core_template_view",
  "core_variable_delete",
  "core_variable_edit",
  "core_variable_view",
]
